my_jaffle_shop:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 35.224.105.219
      user: postgres
      password: R+IRdZP[)BK^T}O-
      port: 5432
      dbname: postgres
      schema: public